/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI.h>
#include <falso_jni/FalsoJNI_Impl.h>
#include <falso_jni/FalsoJNI_Logger.h>
/* Los stubs llaman fjni_logv_dbg() con un solo argumento (sin varargs); la macro
 * upstream deja una coma colgando ("fmt, )"). Redefinicion local con extension GNU
 * para tragar la coma. Si el toolkit regenera este archivo, re-aplicar este bloque. */
#undef fjni_logv_dbg
#define fjni_logv_dbg(fmt, ...) _fjni_log_debug(__FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__)
#include "generated_jni_table.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "utils/utils.h"

// ---- Curados a mano (2026-09-22) contra jadx, para el layout ux0_data/ ----
// GTRacing.getSDFolder/getPathData + SUtils.getSDFolder/getSaveFolder/getOBBFolder/
// getPreferenceString: el .so construye rutas con lo que devuelven; NULL cuelga.
// Ver PORTING_PLAN.md §6 y GTRacing.java:294-310, SUtils.java:218-220,305-316.
#ifndef DATA_PATH
#define DATA_PATH "ux0:data/gtracinghyundaiedition/"
#endif
#define HY_PKG_DIR DATA_PATH "com.gameloft.android.ANMP.GloftGTHY"
#define HY_OBB HY_PKG_DIR "/main.100.com.gameloft.android.ANMP.GloftGTHY.obb"

static jobject hy_str(const char *s) {
    return (jobject)jni->NewStringUTF(&jni, s);
}

static const char *hy_cstr(jobject jstr) {
    if (!jstr) return "";
    const char *s = jni->GetStringUTFChars(&jni, (jstring)jstr, NULL);
    return s ? s : "";
}

// Lee un archivo completo a jbyteArray (NULL si no existe). La ruta pasa por
// el mismo mapa Android->Vita que io.c (hy_rewrite_path).
static jbyteArray hy_read_whole(const char *path) {
    char realp[1024];
    hy_rewrite_path(path, realp, sizeof(realp));
    FILE *f = fopen(realp, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0) { fclose(f); return NULL; }
    jbyteArray arr = jni->NewByteArray(&jni, (jsize)size);
    if (!arr) { fclose(f); return NULL; }
    static jbyte chunk[32768];
    jsize done = 0;
    while (done < (jsize)size) {
        jsize want = (jsize)size - done > (jsize)sizeof(chunk) ? (jsize)sizeof(chunk) : (jsize)size - done;
        size_t got = fread(chunk, 1, (size_t)want, f);
        if (got == 0) break;
        jni->SetByteArrayRegion(&jni, arr, done, (jsize)got, chunk);
        done += (jsize)got;
    }
    fclose(f);
    return arr;
}

// Crea directorios padre (mkdir -p de un nivel: DATA_PATH ya existe).
static void hy_mkparent(const char *path) {
    char tmp[1024];
    snprintf(tmp, sizeof(tmp), "%s", path);
    for (char *p = strchr(tmp + 1, '/'); p; p = strchr(p + 1, '/')) {
        *p = '\0';
        mkdir(tmp, 0777);
        *p = '/';
    }
}

// ---- com.gameloft.android.ANMP.GloftGTHY.CustomFilter ----
jobject stub_CustomFilter_CustomFilter_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.CustomFilter.CustomFilter(I)Lprivate; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jobject stub_CustomFilter_filter_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.CustomFilter.filter(LCharSequence;IILSpanned;II)LCharSequence; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jobject arg3 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg4 = (jint) va_arg(args, int);
    jint arg5 = (jint) va_arg(args, int);
    return NULL;
}

// ---- com.gameloft.android.ANMP.GloftGTHY.EditTextField ----
jobject stub_EditTextField_EditTextField_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.EditTextField.EditTextField(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jboolean stub_EditTextField_onKeyPreIme_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.EditTextField.onKeyPreIme(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

// ---- com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device ----
jobject stub_Device_Device_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.Device()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_DisableWifi_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.DisableWifi()V called -- fill in from the real Java impl (jadx).");
}

void stub_Device_EnableWifi_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.EnableWifi()V called -- fill in from the real Java impl (jadx).");
}

void stub_Device_InitDeviceValues_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.InitDeviceValues()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Device_IsConnectionReady_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.IsConnectionReady()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_Device_IsWifiDisabling_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.IsWifiDisabling()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_Device_IsWifiEnable_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.IsWifiEnable()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_Device_IsWifiEnabling_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.IsWifiEnabling()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_ValidateStringforURL_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.ValidateStringforURL(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jbyteArray stub_Device_a_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.a()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_b_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.b()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_c_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.c()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_createUniqueCode_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.createUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_Device_d_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.d()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_d1_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.d1()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_e_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.e()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_e_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.e(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jbyteArray stub_Device_f_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.f()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getBillingVersion_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getBillingVersion()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getCarrier_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getCarrier()La; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDemoCode_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getDemoCode()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDevice_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getDevice()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDeviceId_26(jmethodID id, va_list args) {
    return hy_str("000000000000000");  // sin RIL en Vita; dummy estable
}

jbyteArray stub_Device_getHostName_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getHostName()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getIMEI_28(jmethodID id, va_list args) {
    return hy_str("000000000000000");  // sin RIL en Vita; dummy estable
}

jboolean stub_Device_getIsRoaming_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getIsRoaming()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_getLanguage_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getLanguage(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jobject stub_Device_getLineNumber_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getLineNumber()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkCountryIso_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getNetworkCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperator_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getNetworkOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperatorName_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getNetworkOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getPhoneModel_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getPhoneModel()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getProfileType_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getProfileType()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimCountryIso_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getSimCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperator_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getSimOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperatorName_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getSimOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_getUniqueCode_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jobject stub_Device_getUserAgent_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.getUserAgent()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_init_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_Device_a_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device.a(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

// ---- com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils ----
jobject stub_SUtils_GetSerialKey_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.GetSerialKey()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SUtils_ReadFile_45(jmethodID id, va_list args) {
    jint arg0 = (jint) va_arg(args, int);
    (void)arg0;
    // ReadFile(int resId): recurso crudo del APK; sin tabla R.raw -> "" (no NULL).
    return hy_str("");
}

jobject stub_SUtils_ReadFile_46(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);
    // SUtils.java:63-74: lee archivo completo a String, null si falla.
    jbyteArray arr = hy_read_whole(hy_cstr(arg0));
    if (!arr) return NULL;
    jsize len = jni->GetArrayLength(&jni, arr);
    char *buf = malloc((size_t)len + 1);
    if (!buf) return NULL;
    jni->GetByteArrayRegion(&jni, arr, 0, len, (jbyte *)buf);
    buf[len] = '\0';
    jobject ret = hy_str(buf);
    free(buf);
    return ret;
}

jbyteArray stub_SUtils_ReadFileByte_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.ReadFileByte(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_SUtils_ReadFileByte_48(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);
    // SUtils.java:89-100: lee archivo completo a byte[], null si falla.
    return hy_read_whole(hy_cstr(arg0));
}

jboolean stub_SUtils_WriteFile_49(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);  // path
    jobject arg1 = (jobject) va_arg(args, jobject);  // data (String)
    // SUtils.java:102-120: mkdirs + escribe texto, true si OK.
    char realp[1024];
    hy_rewrite_path(hy_cstr(arg0), realp, sizeof(realp));
    hy_mkparent(realp);
    const char *data = hy_cstr(arg1);
    FILE *f = fopen(realp, "wb");
    if (!f) return JNI_FALSE;
    size_t n = strlen(data);
    size_t w = n ? fwrite(data, 1, n, f) : 0;
    fclose(f);
    return (w == n) ? JNI_TRUE : JNI_FALSE;
}

jboolean stub_SUtils_WriteFile_50(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);   // path
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);  // data (byte[])
    char realp[1024];
    hy_rewrite_path(hy_cstr(arg0), realp, sizeof(realp));
    hy_mkparent(realp);
    if (!arg1) return JNI_FALSE;
    jsize len = jni->GetArrayLength(&jni, arg1);
    jbyte *buf = malloc((size_t)len ? (size_t)len : 1);
    if (!buf) return JNI_FALSE;
    jni->GetByteArrayRegion(&jni, arg1, 0, len, buf);
    FILE *f = fopen(realp, "wb");
    if (!f) { free(buf); return JNI_FALSE; }
    size_t w = len ? fwrite(buf, 1, (size_t)len, f) : 0;
    fclose(f);
    free(buf);
    return (w == (size_t)len) ? JNI_TRUE : JNI_FALSE;
}

jboolean stub_SUtils_doesZipContains_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.doesZipContains(Ljava/lang/String;Ljava/lang/String;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    return JNI_FALSE;
}

jobject stub_SUtils_extractSOFile_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.extractSOFile(LPair<String;LString>;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jobject stub_SUtils_getContext_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getContext()LContext; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jfloat stub_SUtils_getFreeSpace_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getFreeSpace(Ljava/lang/String;)F called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0.0f;
}

jobject stub_SUtils_getOBBFolder_55(jmethodID id, va_list args) {
    return hy_str(HY_PKG_DIR);  // SUtils.java:218-220
}

jobject stub_SUtils_getOverriddenSetting_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getOverriddenSetting(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    return NULL;
}

jboolean stub_SUtils_getOverriddenSettingBoolean_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getOverriddenSettingBoolean(Ljava/lang/String;Ljava/lang/String;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    return JNI_FALSE;
}

jobject stub_SUtils_getPackage_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPackage()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SUtils_getPhoneDevice_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPhoneDevice()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SUtils_getPhoneManufacture_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPhoneManufacture()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SUtils_getPhoneModel_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPhoneModel()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SUtils_getPhoneProduct_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPhoneProduct()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jboolean stub_SUtils_getPreferenceBoolean_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPreferenceBoolean(Ljava/lang/String;ZLjava/lang/String;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jboolean arg1 = (jboolean) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);
    return JNI_FALSE;
}

jint stub_SUtils_getPreferenceInt_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPreferenceInt(Ljava/lang/String;ILjava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);
    return 0;
}

jlong stub_SUtils_getPreferenceLong_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getPreferenceLong(Ljava/lang/String;JLjava/lang/String;)J called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jlong arg1 = (jlong) va_arg(args, jlong);
    jobject arg2 = (jobject) va_arg(args, jobject);
    return 0;
}

jobject stub_SUtils_getPreferenceString_66(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);  // key
    jobject arg1 = (jobject) va_arg(args, jobject);  // prefsName
    // SUtils.java:305-308: getSDFolder() lee pref "SDFolder", default = hardcode.
    if (strcmp(hy_cstr(arg0), "SDFolder") == 0)
        return hy_str(DATA_PATH);
    return hy_str("");
}

jobject stub_SUtils_getPreferenceString_67(jmethodID id, va_list args) {
    jobject arg0 = (jobject) va_arg(args, jobject);  // key
    jobject arg1 = (jobject) va_arg(args, jobject);  // default
    jobject arg2 = (jobject) va_arg(args, jobject);  // prefsName
    // SUtils.java:293-295 + initializeTheFilesList (MainFileName/PatchFileName/ExtraFile).
    const char *key = hy_cstr(arg0);
    if (strcmp(key, "SDFolder") == 0)
        return hy_str(DATA_PATH);
    if (strcmp(key, "mainFileName") == 0 || strcmp(key, "MainFileName") == 0)
        return hy_str("main.100.com.gameloft.android.ANMP.GloftGTHY.obb");
    if (strcmp(key, "PatchFileName") == 0 || strcmp(key, "patchFileName") == 0 || strcmp(key, "ExtraFile") == 0)
        return hy_str("");
    return arg1;  // default de Java
}

jobject stub_SUtils_getResourceAsStream_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getResourceAsStream(Ljava/lang/String;)LInputStream; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jobject stub_SUtils_getSDFolder_69(jmethodID id, va_list args) {
    return hy_str(DATA_PATH);  // SUtils.java:305-308
}

jobject stub_SUtils_getSaveFolder_70(jmethodID id, va_list args) {
    return hy_str(DATA_PATH "saves");  // SUtils.java:310-316 (getFilesDir)
}

jint stub_SUtils_getUniqueCode_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getUniqueCode(II)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    return 0;
}

jobject stub_SUtils_getVersionInstalled_72(jmethodID id, va_list args) {
    return hy_str("1.0.0");  // SUtils.java:322-328 (fallback del catch)
}

jobject stub_SUtils_getZipPathForFile_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.getZipPathForFile(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

void stub_SUtils_initializeTheFilesList_74(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.initializeTheFilesList()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_SUtils_isAirplaneModeOn_75(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.isAirplaneModeOn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_SUtils_logWindowMessage_76(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.logWindowMessage(LContext;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
}

jobject stub_SUtils_objectArrayToStringArray_77(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.objectArrayToStringArray([Ljava/lang/Object;)[Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jobject stub_SUtils_readTextFile_78(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.readTextFile(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    return NULL;
}

void stub_SUtils_release_79(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.release()V called -- fill in from the real Java impl (jadx).");
}

void stub_SUtils_resetValusForMAinAndPatch_80(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.resetValusForMAinAndPatch()V called -- fill in from the real Java impl (jadx).");
}

void stub_SUtils_runOnUiThread_81(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.runOnUiThread(LRunnable;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_SUtils_saveLocation_82(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.saveLocation(LSharedPreferences.Editor;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_SUtils_setAirplaneMode_83(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.setAirplaneMode(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_SUtils_setContext_84(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.setContext(LContext;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_SUtils_setOverriddenSetting_85(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.setOverriddenSetting(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_SUtils_setPreference_86(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.setPreference(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_SUtils_shareInfo_87(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils.shareInfo(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

// ---- com.gameloft.android.ANMP.GloftGTHY.GTRacing ----
void stub_GTRacing_DismissLoading_88(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.DismissLoading()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_HideFacebookDialog_89(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.HideFacebookDialog()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_ShowFacebookDialog_90(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.ShowFacebookDialog()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_TrackAndroidHits_91(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.TrackAndroidHits(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GTRacing_a_92(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.a()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_a_93(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.a(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

jboolean stub_GTRacing_b_94(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.b()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GTRacing_c_95(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.c()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_GTRacing_checkDeviceName_96(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.checkDeviceName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_GTRacing_checkManufacturer_97(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.checkManufacturer()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_GTRacing_ensurePathExists_98(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.ensurePathExists(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

jobject stub_GTRacing_getCrtTimeStr_99(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.getCrtTimeStr()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_GTRacing_getIMEI_100(jmethodID id, va_list args) {
    return hy_str("000000000000000");
}

jobject stub_GTRacing_getMac_101(jmethodID id, va_list args) {
    return hy_str("00:00:00:00:00:00");
}

jint stub_GTRacing_getManufacture_102(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.getManufacture()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jobject stub_GTRacing_getPathData_103(jmethodID id, va_list args) {
    // GTRacing.java:294-298: /sdcard/Android/obb/<pkg>/ + pref mainFileName.
    // El rewrite de io.c lo mapea al OBB real en Vita.
    return hy_str("/sdcard/Android/obb/com.gameloft.android.ANMP.GloftGTHY/main.100.com.gameloft.android.ANMP.GloftGTHY.obb");
}

jobject stub_GTRacing_getSDFolder_104(jmethodID id, va_list args) {
    return hy_str(DATA_PATH);  // GTRacing.java:300-310
}

jobject stub_GTRacing_getUniqueId_105(jmethodID id, va_list args) {
    return hy_str("VITA-HYUNDAI-0001");  // Device.getDeviceId() en Java; dummy estable
}

jboolean stub_GTRacing_isNeedInvertTouchZone_106(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.isNeedInvertTouchZone()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_GTRacing_isUseLowres_107(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.isUseLowres()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GTRacing_launchGLLive_108(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.launchGLLive(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GTRacing_launchIGP_109(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.launchIGP(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GTRacing_notifyTrophy_110(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.notifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GTRacing_resumeScreen_111(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.resumeScreen()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_setTypeText_112(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.setTypeText(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GTRacing_setupPaths_113(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.setupPaths()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_CreateContentView_114(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.CreateContentView()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GTRacing_EnableAutoRotateScreen_115(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.EnableAutoRotateScreen(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jboolean stub_GTRacing_IsKeyboardEnabled_116(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.IsKeyboardEnabled(LConfiguration;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GTRacing_exit_117(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.exit()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_GTRacing_getCurrentVersion_118(jmethodID id, va_list args) {
    return hy_str("1.0.0");  // se compara con oconf.bar (GTRacing.java:180,612)
}

void stub_GTRacing_gotoMarket_119(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.gotoMarket()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GTRacing_isWifiAlive_120(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.isWifiAlive()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_GTRacing_onAccuracyChanged_121(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onAccuracyChanged(LSensor;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GTRacing_onActivityResult_122(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_onConfigurationChanged_123(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onConfigurationChanged(LConfiguration;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_onCreate_124(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_onDestroy_125(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_onGlobalLayout_126(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onGlobalLayout()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GTRacing_onKeyDown_127(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_GTRacing_onKeyUp_128(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GTRacing_onNewIntent_129(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onNewIntent(LIntent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_onPause_130(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_onRestart_131(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_onResume_132(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_onSensorChanged_133(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onSensorChanged(LSensorEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_onStart_134(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_onStop_135(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onStop()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_GTRacing_onTouchEvent_136(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GTRacing_onUserInteraction_137(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.onUserInteraction()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_openCustomerCare_138(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.openCustomerCare()V called -- fill in from the real Java impl (jadx).");
}

void stub_GTRacing_showOffersWithCurrencyID_139(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.showOffersWithCurrencyID(Ljava/lang/String;Z)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jboolean arg1 = (jboolean) va_arg(args, int);
}

void stub_GTRacing_surfaceChanged_140(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.surfaceChanged(LSurfaceHolder;III)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

void stub_GTRacing_surfaceCreated_141(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.surfaceCreated(LSurfaceHolder;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GTRacing_surfaceDestroyed_142(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GTRacing.surfaceDestroyed(LSurfaceHolder;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView ----
jobject stub_GameGLSurfaceView_GameGLSurfaceView_143(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView.GameGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameGLSurfaceView_onPause_144(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_GameGLSurfaceView_onResume_145(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_GameGLSurfaceView_onSizeChanged_146(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

void stub_GameGLSurfaceView_onWindowFocusChanged_147(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.gameloft.android.ANMP.GloftGTHY.GameRenderer ----
jobject stub_GameRenderer_GameRenderer_148(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameRenderer.GameRenderer(LContext;)Lprivate; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameRenderer_onDrawFrame_149(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameRenderer_onSurfaceChanged_150(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GameRenderer_onSurfaceCreated_151(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.GameRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity ----
jobject stub_IGPFreemiumActivity_IGPFreemiumActivity_152(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.IGPFreemiumActivity()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_IGPFreemiumActivity_a_153(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.a(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_IGPFreemiumActivity_a_154(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.a(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IGPFreemiumActivity_b_155(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.b(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

jobject stub_IGPFreemiumActivity_getHttpResponse_156(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.getHttpResponse(Ljava.lang.String;)Ljava.lang.String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_IGPFreemiumActivity_a_157(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.a()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPFreemiumActivity_onCreate_158(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IGPFreemiumActivity_onDestroy_159(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_IGPFreemiumActivity_onKeyDown_160(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_IGPFreemiumActivity_onKeyLongPress_161(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onKeyLongPress(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_IGPFreemiumActivity_onKeyUp_162(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_IGPFreemiumActivity_onPause_163(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPFreemiumActivity_onResume_164(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPFreemiumActivity_onStart_165(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPFreemiumActivity_onStop_166(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_IGPFreemiumActivity_onWindowFocusChanged_167(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.gameloft.android.ANMP.GloftGTHY.KeyboardInput ----
void stub_KeyboardInput_onCreate_168(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.KeyboardInput.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jboolean stub_KeyboardInput_onKeyDown_169(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.KeyboardInput.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_KeyboardInput_onKeyUp_170(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.KeyboardInput.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

// ---- com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib ----
jobject stub_FacebookAndroidGLSocialLib_FacebookAndroidGLSocialLib_171(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.FacebookAndroidGLSocialLib(LActivity;LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_FacebookAndroidGLSocialLib_AuthorizeSSOCallback_172(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.AuthorizeSSOCallback(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_FacebookAndroidGLSocialLib_ClearAuth_173(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.ClearAuth()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_GetFriends_174(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.GetFriends()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_GetFriendsInGame_175(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.GetFriendsInGame()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_GetMyInfo_176(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.GetMyInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_GetPicture_177(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.GetPicture()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_GetUserData_178(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.GetUserData(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_FacebookAndroidGLSocialLib_Init_179(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.Init()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_InviteFriends_180(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.InviteFriends(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_FacebookAndroidGLSocialLib_InviteFriends_facade_181(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.InviteFriends_facade(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

jboolean stub_FacebookAndroidGLSocialLib_IsLoggedIn_182(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.IsLoggedIn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jboolean stub_FacebookAndroidGLSocialLib_LoadAuth_183(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.LoadAuth()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_FacebookAndroidGLSocialLib_Login_184(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.Login()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_Login_facade_185(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.Login_facade()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_Logout_186(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.Logout()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookAndroidGLSocialLib_PostToFriendsWall_187(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.PostToFriendsWall(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jobject arg3 = (jobject) va_arg(args, jobject);
    jobject arg4 = (jobject) va_arg(args, jobject);
    jobject arg5 = (jobject) va_arg(args, jobject);
}

void stub_FacebookAndroidGLSocialLib_PostToFriendsWall_facade_188(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.PostToFriendsWall_facade(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jobject arg3 = (jobject) va_arg(args, jobject);
    jobject arg4 = (jobject) va_arg(args, jobject);
    jobject arg5 = (jobject) va_arg(args, jobject);
}

void stub_FacebookAndroidGLSocialLib_PostToWall_189(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.PostToWall(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jobject arg3 = (jobject) va_arg(args, jobject);
    jobject arg4 = (jobject) va_arg(args, jobject);
}

void stub_FacebookAndroidGLSocialLib_PostToWall_facade_190(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.PostToWall_facade(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jobject arg3 = (jobject) va_arg(args, jobject);
    jobject arg4 = (jobject) va_arg(args, jobject);
}

jboolean stub_FacebookAndroidGLSocialLib_SaveAuth_191(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.SaveAuth()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_FacebookAndroidGLSocialLib_SetAppId_192(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib.SetAppId(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

