/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jobject stub_CustomFilter_CustomFilter_0(jmethodID id, va_list args);
extern jobject stub_CustomFilter_filter_1(jmethodID id, va_list args);
extern jobject stub_EditTextField_EditTextField_2(jmethodID id, va_list args);
extern jboolean stub_EditTextField_onKeyPreIme_3(jmethodID id, va_list args);
extern jobject stub_Device_Device_4(jmethodID id, va_list args);
extern void stub_Device_DisableWifi_5(jmethodID id, va_list args);
extern void stub_Device_EnableWifi_6(jmethodID id, va_list args);
extern void stub_Device_InitDeviceValues_7(jmethodID id, va_list args);
extern jboolean stub_Device_IsConnectionReady_8(jmethodID id, va_list args);
extern jboolean stub_Device_IsWifiDisabling_9(jmethodID id, va_list args);
extern jboolean stub_Device_IsWifiEnable_10(jmethodID id, va_list args);
extern jboolean stub_Device_IsWifiEnabling_11(jmethodID id, va_list args);
extern jobject stub_Device_ValidateStringforURL_12(jmethodID id, va_list args);
extern jobject stub_Device_a_13(jmethodID id, va_list args);
extern jobject stub_Device_b_14(jmethodID id, va_list args);
extern jobject stub_Device_c_15(jmethodID id, va_list args);
extern jint stub_Device_createUniqueCode_16(jmethodID id, va_list args);
extern jobject stub_Device_d_17(jmethodID id, va_list args);
extern jobject stub_Device_d1_18(jmethodID id, va_list args);
extern jobject stub_Device_e_19(jmethodID id, va_list args);
extern void stub_Device_e_20(jmethodID id, va_list args);
extern jobject stub_Device_f_21(jmethodID id, va_list args);
extern jobject stub_Device_getBillingVersion_22(jmethodID id, va_list args);
extern jobject stub_Device_getCarrier_23(jmethodID id, va_list args);
extern jobject stub_Device_getDemoCode_24(jmethodID id, va_list args);
extern jobject stub_Device_getDevice_25(jmethodID id, va_list args);
extern jobject stub_Device_getDeviceId_26(jmethodID id, va_list args);
extern jobject stub_Device_getHostName_27(jmethodID id, va_list args);
extern jobject stub_Device_getIMEI_28(jmethodID id, va_list args);
extern jboolean stub_Device_getIsRoaming_29(jmethodID id, va_list args);
extern jobject stub_Device_getLanguage_30(jmethodID id, va_list args);
extern jobject stub_Device_getLineNumber_31(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkCountryIso_32(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperator_33(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperatorName_34(jmethodID id, va_list args);
extern jobject stub_Device_getPhoneModel_35(jmethodID id, va_list args);
extern jobject stub_Device_getProfileType_36(jmethodID id, va_list args);
extern jobject stub_Device_getSimCountryIso_37(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperator_38(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperatorName_39(jmethodID id, va_list args);
extern jint stub_Device_getUniqueCode_40(jmethodID id, va_list args);
extern jobject stub_Device_getUserAgent_41(jmethodID id, va_list args);
extern void stub_Device_init_42(jmethodID id, va_list args);
extern void stub_Device_a_43(jmethodID id, va_list args);
extern jobject stub_SUtils_GetSerialKey_44(jmethodID id, va_list args);
extern jobject stub_SUtils_ReadFile_45(jmethodID id, va_list args);
extern jobject stub_SUtils_ReadFile_46(jmethodID id, va_list args);
extern jobject stub_SUtils_ReadFileByte_47(jmethodID id, va_list args);
extern jobject stub_SUtils_ReadFileByte_48(jmethodID id, va_list args);
extern jboolean stub_SUtils_WriteFile_49(jmethodID id, va_list args);
extern jboolean stub_SUtils_WriteFile_50(jmethodID id, va_list args);
extern jboolean stub_SUtils_doesZipContains_51(jmethodID id, va_list args);
extern jobject stub_SUtils_extractSOFile_52(jmethodID id, va_list args);
extern jobject stub_SUtils_getContext_53(jmethodID id, va_list args);
extern jfloat stub_SUtils_getFreeSpace_54(jmethodID id, va_list args);
extern jobject stub_SUtils_getOBBFolder_55(jmethodID id, va_list args);
extern jobject stub_SUtils_getOverriddenSetting_56(jmethodID id, va_list args);
extern jboolean stub_SUtils_getOverriddenSettingBoolean_57(jmethodID id, va_list args);
extern jobject stub_SUtils_getPackage_58(jmethodID id, va_list args);
extern jobject stub_SUtils_getPhoneDevice_59(jmethodID id, va_list args);
extern jobject stub_SUtils_getPhoneManufacture_60(jmethodID id, va_list args);
extern jobject stub_SUtils_getPhoneModel_61(jmethodID id, va_list args);
extern jobject stub_SUtils_getPhoneProduct_62(jmethodID id, va_list args);
extern jboolean stub_SUtils_getPreferenceBoolean_63(jmethodID id, va_list args);
extern jint stub_SUtils_getPreferenceInt_64(jmethodID id, va_list args);
extern jlong stub_SUtils_getPreferenceLong_65(jmethodID id, va_list args);
extern jobject stub_SUtils_getPreferenceString_66(jmethodID id, va_list args);
extern jobject stub_SUtils_getPreferenceString_67(jmethodID id, va_list args);
extern jobject stub_SUtils_getResourceAsStream_68(jmethodID id, va_list args);
extern jobject stub_SUtils_getSDFolder_69(jmethodID id, va_list args);
extern jobject stub_SUtils_getSaveFolder_70(jmethodID id, va_list args);
extern jint stub_SUtils_getUniqueCode_71(jmethodID id, va_list args);
extern jobject stub_SUtils_getVersionInstalled_72(jmethodID id, va_list args);
extern jobject stub_SUtils_getZipPathForFile_73(jmethodID id, va_list args);
extern void stub_SUtils_initializeTheFilesList_74(jmethodID id, va_list args);
extern jboolean stub_SUtils_isAirplaneModeOn_75(jmethodID id, va_list args);
extern void stub_SUtils_logWindowMessage_76(jmethodID id, va_list args);
extern jobject stub_SUtils_objectArrayToStringArray_77(jmethodID id, va_list args);
extern jobject stub_SUtils_readTextFile_78(jmethodID id, va_list args);
extern void stub_SUtils_release_79(jmethodID id, va_list args);
extern void stub_SUtils_resetValusForMAinAndPatch_80(jmethodID id, va_list args);
extern void stub_SUtils_runOnUiThread_81(jmethodID id, va_list args);
extern void stub_SUtils_saveLocation_82(jmethodID id, va_list args);
extern void stub_SUtils_setAirplaneMode_83(jmethodID id, va_list args);
extern void stub_SUtils_setContext_84(jmethodID id, va_list args);
extern void stub_SUtils_setOverriddenSetting_85(jmethodID id, va_list args);
extern void stub_SUtils_setPreference_86(jmethodID id, va_list args);
extern void stub_SUtils_shareInfo_87(jmethodID id, va_list args);
extern void stub_GTRacing_DismissLoading_88(jmethodID id, va_list args);
extern void stub_GTRacing_HideFacebookDialog_89(jmethodID id, va_list args);
extern void stub_GTRacing_ShowFacebookDialog_90(jmethodID id, va_list args);
extern void stub_GTRacing_TrackAndroidHits_91(jmethodID id, va_list args);
extern void stub_GTRacing_a_92(jmethodID id, va_list args);
extern void stub_GTRacing_a_93(jmethodID id, va_list args);
extern jboolean stub_GTRacing_b_94(jmethodID id, va_list args);
extern void stub_GTRacing_c_95(jmethodID id, va_list args);
extern jobject stub_GTRacing_checkDeviceName_96(jmethodID id, va_list args);
extern jobject stub_GTRacing_checkManufacturer_97(jmethodID id, va_list args);
extern void stub_GTRacing_ensurePathExists_98(jmethodID id, va_list args);
extern jobject stub_GTRacing_getCrtTimeStr_99(jmethodID id, va_list args);
extern jobject stub_GTRacing_getIMEI_100(jmethodID id, va_list args);
extern jobject stub_GTRacing_getMac_101(jmethodID id, va_list args);
extern jint stub_GTRacing_getManufacture_102(jmethodID id, va_list args);
extern jobject stub_GTRacing_getPathData_103(jmethodID id, va_list args);
extern jobject stub_GTRacing_getSDFolder_104(jmethodID id, va_list args);
extern jobject stub_GTRacing_getUniqueId_105(jmethodID id, va_list args);
extern jboolean stub_GTRacing_isNeedInvertTouchZone_106(jmethodID id, va_list args);
extern jboolean stub_GTRacing_isUseLowres_107(jmethodID id, va_list args);
extern void stub_GTRacing_launchGLLive_108(jmethodID id, va_list args);
extern void stub_GTRacing_launchIGP_109(jmethodID id, va_list args);
extern void stub_GTRacing_notifyTrophy_110(jmethodID id, va_list args);
extern void stub_GTRacing_resumeScreen_111(jmethodID id, va_list args);
extern void stub_GTRacing_setTypeText_112(jmethodID id, va_list args);
extern void stub_GTRacing_setupPaths_113(jmethodID id, va_list args);
extern void stub_GTRacing_CreateContentView_114(jmethodID id, va_list args);
extern jint stub_GTRacing_EnableAutoRotateScreen_115(jmethodID id, va_list args);
extern jboolean stub_GTRacing_IsKeyboardEnabled_116(jmethodID id, va_list args);
extern void stub_GTRacing_exit_117(jmethodID id, va_list args);
extern jobject stub_GTRacing_getCurrentVersion_118(jmethodID id, va_list args);
extern void stub_GTRacing_gotoMarket_119(jmethodID id, va_list args);
extern jboolean stub_GTRacing_isWifiAlive_120(jmethodID id, va_list args);
extern void stub_GTRacing_onAccuracyChanged_121(jmethodID id, va_list args);
extern void stub_GTRacing_onActivityResult_122(jmethodID id, va_list args);
extern void stub_GTRacing_onConfigurationChanged_123(jmethodID id, va_list args);
extern void stub_GTRacing_onCreate_124(jmethodID id, va_list args);
extern void stub_GTRacing_onDestroy_125(jmethodID id, va_list args);
extern void stub_GTRacing_onGlobalLayout_126(jmethodID id, va_list args);
extern jboolean stub_GTRacing_onKeyDown_127(jmethodID id, va_list args);
extern jboolean stub_GTRacing_onKeyUp_128(jmethodID id, va_list args);
extern void stub_GTRacing_onNewIntent_129(jmethodID id, va_list args);
extern void stub_GTRacing_onPause_130(jmethodID id, va_list args);
extern void stub_GTRacing_onRestart_131(jmethodID id, va_list args);
extern void stub_GTRacing_onResume_132(jmethodID id, va_list args);
extern void stub_GTRacing_onSensorChanged_133(jmethodID id, va_list args);
extern void stub_GTRacing_onStart_134(jmethodID id, va_list args);
extern void stub_GTRacing_onStop_135(jmethodID id, va_list args);
extern jboolean stub_GTRacing_onTouchEvent_136(jmethodID id, va_list args);
extern void stub_GTRacing_onUserInteraction_137(jmethodID id, va_list args);
extern void stub_GTRacing_openCustomerCare_138(jmethodID id, va_list args);
extern void stub_GTRacing_showOffersWithCurrencyID_139(jmethodID id, va_list args);
extern void stub_GTRacing_surfaceChanged_140(jmethodID id, va_list args);
extern void stub_GTRacing_surfaceCreated_141(jmethodID id, va_list args);
extern void stub_GTRacing_surfaceDestroyed_142(jmethodID id, va_list args);
extern jobject stub_GameGLSurfaceView_GameGLSurfaceView_143(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onPause_144(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onResume_145(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onSizeChanged_146(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onWindowFocusChanged_147(jmethodID id, va_list args);
extern jobject stub_GameRenderer_GameRenderer_148(jmethodID id, va_list args);
extern void stub_GameRenderer_onDrawFrame_149(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceChanged_150(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceCreated_151(jmethodID id, va_list args);
extern jobject stub_IGPFreemiumActivity_IGPFreemiumActivity_152(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_a_153(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_a_154(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_b_155(jmethodID id, va_list args);
extern jobject stub_IGPFreemiumActivity_getHttpResponse_156(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_a_157(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onCreate_158(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onDestroy_159(jmethodID id, va_list args);
extern jboolean stub_IGPFreemiumActivity_onKeyDown_160(jmethodID id, va_list args);
extern jboolean stub_IGPFreemiumActivity_onKeyLongPress_161(jmethodID id, va_list args);
extern jboolean stub_IGPFreemiumActivity_onKeyUp_162(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onPause_163(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onResume_164(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onStart_165(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onStop_166(jmethodID id, va_list args);
extern void stub_IGPFreemiumActivity_onWindowFocusChanged_167(jmethodID id, va_list args);
extern void stub_KeyboardInput_onCreate_168(jmethodID id, va_list args);
extern jboolean stub_KeyboardInput_onKeyDown_169(jmethodID id, va_list args);
extern jboolean stub_KeyboardInput_onKeyUp_170(jmethodID id, va_list args);
extern jobject stub_FacebookAndroidGLSocialLib_FacebookAndroidGLSocialLib_171(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_AuthorizeSSOCallback_172(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_ClearAuth_173(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_GetFriends_174(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_GetFriendsInGame_175(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_GetMyInfo_176(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_GetPicture_177(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_GetUserData_178(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_Init_179(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_InviteFriends_180(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_InviteFriends_facade_181(jmethodID id, va_list args);
extern jboolean stub_FacebookAndroidGLSocialLib_IsLoggedIn_182(jmethodID id, va_list args);
extern jboolean stub_FacebookAndroidGLSocialLib_LoadAuth_183(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_Login_184(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_Login_facade_185(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_Logout_186(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_PostToFriendsWall_187(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_PostToFriendsWall_facade_188(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_PostToWall_189(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_PostToWall_facade_190(jmethodID id, va_list args);
extern jboolean stub_FacebookAndroidGLSocialLib_SaveAuth_191(jmethodID id, va_list args);
extern void stub_FacebookAndroidGLSocialLib_SetAppId_192(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "CustomFilter", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.CustomFilter
    { 1, "filter", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.CustomFilter
    { 2, "EditTextField", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.EditTextField
    { 3, "onKeyPreIme", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.EditTextField
    { 4, "Device", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 5, "DisableWifi", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 6, "EnableWifi", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 7, "InitDeviceValues", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 8, "IsConnectionReady", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 9, "IsWifiDisabling", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 10, "IsWifiEnable", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 11, "IsWifiEnabling", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 12, "ValidateStringforURL", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 13, "a", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 14, "b", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 15, "c", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 16, "createUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 17, "d", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 18, "d1", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 19, "e", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 20, "e", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 21, "f", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 22, "getBillingVersion", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 23, "getCarrier", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 24, "getDemoCode", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 25, "getDevice", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 26, "getDeviceId", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 27, "getHostName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 28, "getIMEI", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 29, "getIsRoaming", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 30, "getLanguage", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 31, "getLineNumber", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 32, "getNetworkCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 33, "getNetworkOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 34, "getNetworkOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 35, "getPhoneModel", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 36, "getProfileType", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 37, "getSimCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 38, "getSimOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 39, "getSimOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 40, "getUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 41, "getUserAgent", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 42, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 43, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.Device
    { 44, "GetSerialKey", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 45, "ReadFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 46, "ReadFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 47, "ReadFileByte", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 48, "ReadFileByte", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 49, "WriteFile", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 50, "WriteFile", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 51, "doesZipContains", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 52, "extractSOFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 53, "getContext", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 54, "getFreeSpace", METHOD_TYPE_FLOAT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 55, "getOBBFolder", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 56, "getOverriddenSetting", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 57, "getOverriddenSettingBoolean", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 58, "getPackage", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 59, "getPhoneDevice", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 60, "getPhoneManufacture", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 61, "getPhoneModel", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 62, "getPhoneProduct", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 63, "getPreferenceBoolean", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 64, "getPreferenceInt", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 65, "getPreferenceLong", METHOD_TYPE_LONG },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 66, "getPreferenceString", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 67, "getPreferenceString", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 68, "getResourceAsStream", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 69, "getSDFolder", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 70, "getSaveFolder", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 71, "getUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 72, "getVersionInstalled", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 73, "getZipPathForFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 74, "initializeTheFilesList", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 75, "isAirplaneModeOn", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 76, "logWindowMessage", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 77, "objectArrayToStringArray", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 78, "readTextFile", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 79, "release", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 80, "resetValusForMAinAndPatch", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 81, "runOnUiThread", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 82, "saveLocation", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 83, "setAirplaneMode", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 84, "setContext", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 85, "setOverriddenSetting", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 86, "setPreference", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 87, "shareInfo", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GLUtils.SUtils
    { 88, "DismissLoading", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 89, "HideFacebookDialog", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 90, "ShowFacebookDialog", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 91, "TrackAndroidHits", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 92, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 93, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 94, "b", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 95, "c", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 96, "checkDeviceName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 97, "checkManufacturer", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 98, "ensurePathExists", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 99, "getCrtTimeStr", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 100, "getIMEI", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 101, "getMac", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 102, "getManufacture", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 103, "getPathData", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 104, "getSDFolder", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 105, "getUniqueId", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 106, "isNeedInvertTouchZone", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 107, "isUseLowres", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 108, "launchGLLive", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 109, "launchIGP", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 110, "notifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 111, "resumeScreen", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 112, "setTypeText", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 113, "setupPaths", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 114, "CreateContentView", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 115, "EnableAutoRotateScreen", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 116, "IsKeyboardEnabled", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 117, "exit", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 118, "getCurrentVersion", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 119, "gotoMarket", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 120, "isWifiAlive", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 121, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 122, "onActivityResult", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 123, "onConfigurationChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 124, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 125, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 126, "onGlobalLayout", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 127, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 128, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 129, "onNewIntent", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 130, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 131, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 132, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 133, "onSensorChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 134, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 135, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 136, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 137, "onUserInteraction", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 138, "openCustomerCare", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 139, "showOffersWithCurrencyID", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 140, "surfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 141, "surfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 142, "surfaceDestroyed", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GTRacing
    { 143, "GameGLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView
    { 144, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView
    { 145, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView
    { 146, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView
    { 147, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameGLSurfaceView
    { 148, "GameRenderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.GameRenderer
    { 149, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameRenderer
    { 150, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameRenderer
    { 151, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.GameRenderer
    { 152, "IGPFreemiumActivity", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 153, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 154, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 155, "b", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 156, "getHttpResponse", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 157, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 158, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 159, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 160, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 161, "onKeyLongPress", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 162, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 163, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 164, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 165, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 166, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 167, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.IGPFreemiumActivity
    { 168, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.KeyboardInput
    { 169, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.KeyboardInput
    { 170, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.KeyboardInput
    { 171, "FacebookAndroidGLSocialLib", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 172, "AuthorizeSSOCallback", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 173, "ClearAuth", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 174, "GetFriends", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 175, "GetFriendsInGame", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 176, "GetMyInfo", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 177, "GetPicture", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 178, "GetUserData", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 179, "Init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 180, "InviteFriends", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 181, "InviteFriends_facade", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 182, "IsLoggedIn", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 183, "LoadAuth", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 184, "Login", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 185, "Login_facade", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 186, "Logout", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 187, "PostToFriendsWall", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 188, "PostToFriendsWall_facade", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 189, "PostToWall", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 190, "PostToWall_facade", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 191, "SaveAuth", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
    { 192, "SetAppId", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftGTHY.glsociallib.facebook.FacebookAndroidGLSocialLib
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 0, stub_CustomFilter_CustomFilter_0 },
    { 1, stub_CustomFilter_filter_1 },
    { 2, stub_EditTextField_EditTextField_2 },
    { 4, stub_Device_Device_4 },
    { 12, stub_Device_ValidateStringforURL_12 },
    { 13, stub_Device_a_13 },
    { 14, stub_Device_b_14 },
    { 15, stub_Device_c_15 },
    { 17, stub_Device_d_17 },
    { 18, stub_Device_d1_18 },
    { 19, stub_Device_e_19 },
    { 21, stub_Device_f_21 },
    { 22, stub_Device_getBillingVersion_22 },
    { 23, stub_Device_getCarrier_23 },
    { 24, stub_Device_getDemoCode_24 },
    { 25, stub_Device_getDevice_25 },
    { 26, stub_Device_getDeviceId_26 },
    { 27, stub_Device_getHostName_27 },
    { 28, stub_Device_getIMEI_28 },
    { 30, stub_Device_getLanguage_30 },
    { 31, stub_Device_getLineNumber_31 },
    { 32, stub_Device_getNetworkCountryIso_32 },
    { 33, stub_Device_getNetworkOperator_33 },
    { 34, stub_Device_getNetworkOperatorName_34 },
    { 35, stub_Device_getPhoneModel_35 },
    { 36, stub_Device_getProfileType_36 },
    { 37, stub_Device_getSimCountryIso_37 },
    { 38, stub_Device_getSimOperator_38 },
    { 39, stub_Device_getSimOperatorName_39 },
    { 41, stub_Device_getUserAgent_41 },
    { 44, stub_SUtils_GetSerialKey_44 },
    { 45, stub_SUtils_ReadFile_45 },
    { 46, stub_SUtils_ReadFile_46 },
    { 47, stub_SUtils_ReadFileByte_47 },
    { 48, stub_SUtils_ReadFileByte_48 },
    { 52, stub_SUtils_extractSOFile_52 },
    { 53, stub_SUtils_getContext_53 },
    { 55, stub_SUtils_getOBBFolder_55 },
    { 56, stub_SUtils_getOverriddenSetting_56 },
    { 58, stub_SUtils_getPackage_58 },
    { 59, stub_SUtils_getPhoneDevice_59 },
    { 60, stub_SUtils_getPhoneManufacture_60 },
    { 61, stub_SUtils_getPhoneModel_61 },
    { 62, stub_SUtils_getPhoneProduct_62 },
    { 66, stub_SUtils_getPreferenceString_66 },
    { 67, stub_SUtils_getPreferenceString_67 },
    { 68, stub_SUtils_getResourceAsStream_68 },
    { 69, stub_SUtils_getSDFolder_69 },
    { 70, stub_SUtils_getSaveFolder_70 },
    { 72, stub_SUtils_getVersionInstalled_72 },
    { 73, stub_SUtils_getZipPathForFile_73 },
    { 77, stub_SUtils_objectArrayToStringArray_77 },
    { 78, stub_SUtils_readTextFile_78 },
    { 96, stub_GTRacing_checkDeviceName_96 },
    { 97, stub_GTRacing_checkManufacturer_97 },
    { 99, stub_GTRacing_getCrtTimeStr_99 },
    { 100, stub_GTRacing_getIMEI_100 },
    { 101, stub_GTRacing_getMac_101 },
    { 103, stub_GTRacing_getPathData_103 },
    { 104, stub_GTRacing_getSDFolder_104 },
    { 105, stub_GTRacing_getUniqueId_105 },
    { 118, stub_GTRacing_getCurrentVersion_118 },
    { 143, stub_GameGLSurfaceView_GameGLSurfaceView_143 },
    { 148, stub_GameRenderer_GameRenderer_148 },
    { 152, stub_IGPFreemiumActivity_IGPFreemiumActivity_152 },
    { 156, stub_IGPFreemiumActivity_getHttpResponse_156 },
    { 171, stub_FacebookAndroidGLSocialLib_FacebookAndroidGLSocialLib_171 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 3, stub_EditTextField_onKeyPreIme_3 },
    { 8, stub_Device_IsConnectionReady_8 },
    { 9, stub_Device_IsWifiDisabling_9 },
    { 10, stub_Device_IsWifiEnable_10 },
    { 11, stub_Device_IsWifiEnabling_11 },
    { 29, stub_Device_getIsRoaming_29 },
    { 49, stub_SUtils_WriteFile_49 },
    { 50, stub_SUtils_WriteFile_50 },
    { 51, stub_SUtils_doesZipContains_51 },
    { 57, stub_SUtils_getOverriddenSettingBoolean_57 },
    { 63, stub_SUtils_getPreferenceBoolean_63 },
    { 75, stub_SUtils_isAirplaneModeOn_75 },
    { 94, stub_GTRacing_b_94 },
    { 106, stub_GTRacing_isNeedInvertTouchZone_106 },
    { 107, stub_GTRacing_isUseLowres_107 },
    { 116, stub_GTRacing_IsKeyboardEnabled_116 },
    { 120, stub_GTRacing_isWifiAlive_120 },
    { 127, stub_GTRacing_onKeyDown_127 },
    { 128, stub_GTRacing_onKeyUp_128 },
    { 136, stub_GTRacing_onTouchEvent_136 },
    { 160, stub_IGPFreemiumActivity_onKeyDown_160 },
    { 161, stub_IGPFreemiumActivity_onKeyLongPress_161 },
    { 162, stub_IGPFreemiumActivity_onKeyUp_162 },
    { 169, stub_KeyboardInput_onKeyDown_169 },
    { 170, stub_KeyboardInput_onKeyUp_170 },
    { 182, stub_FacebookAndroidGLSocialLib_IsLoggedIn_182 },
    { 183, stub_FacebookAndroidGLSocialLib_LoadAuth_183 },
    { 191, stub_FacebookAndroidGLSocialLib_SaveAuth_191 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 5, stub_Device_DisableWifi_5 },
    { 6, stub_Device_EnableWifi_6 },
    { 7, stub_Device_InitDeviceValues_7 },
    { 20, stub_Device_e_20 },
    { 42, stub_Device_init_42 },
    { 43, stub_Device_a_43 },
    { 74, stub_SUtils_initializeTheFilesList_74 },
    { 76, stub_SUtils_logWindowMessage_76 },
    { 79, stub_SUtils_release_79 },
    { 80, stub_SUtils_resetValusForMAinAndPatch_80 },
    { 81, stub_SUtils_runOnUiThread_81 },
    { 82, stub_SUtils_saveLocation_82 },
    { 83, stub_SUtils_setAirplaneMode_83 },
    { 84, stub_SUtils_setContext_84 },
    { 85, stub_SUtils_setOverriddenSetting_85 },
    { 86, stub_SUtils_setPreference_86 },
    { 87, stub_SUtils_shareInfo_87 },
    { 88, stub_GTRacing_DismissLoading_88 },
    { 89, stub_GTRacing_HideFacebookDialog_89 },
    { 90, stub_GTRacing_ShowFacebookDialog_90 },
    { 91, stub_GTRacing_TrackAndroidHits_91 },
    { 92, stub_GTRacing_a_92 },
    { 93, stub_GTRacing_a_93 },
    { 95, stub_GTRacing_c_95 },
    { 98, stub_GTRacing_ensurePathExists_98 },
    { 108, stub_GTRacing_launchGLLive_108 },
    { 109, stub_GTRacing_launchIGP_109 },
    { 110, stub_GTRacing_notifyTrophy_110 },
    { 111, stub_GTRacing_resumeScreen_111 },
    { 112, stub_GTRacing_setTypeText_112 },
    { 113, stub_GTRacing_setupPaths_113 },
    { 114, stub_GTRacing_CreateContentView_114 },
    { 117, stub_GTRacing_exit_117 },
    { 119, stub_GTRacing_gotoMarket_119 },
    { 121, stub_GTRacing_onAccuracyChanged_121 },
    { 122, stub_GTRacing_onActivityResult_122 },
    { 123, stub_GTRacing_onConfigurationChanged_123 },
    { 124, stub_GTRacing_onCreate_124 },
    { 125, stub_GTRacing_onDestroy_125 },
    { 126, stub_GTRacing_onGlobalLayout_126 },
    { 129, stub_GTRacing_onNewIntent_129 },
    { 130, stub_GTRacing_onPause_130 },
    { 131, stub_GTRacing_onRestart_131 },
    { 132, stub_GTRacing_onResume_132 },
    { 133, stub_GTRacing_onSensorChanged_133 },
    { 134, stub_GTRacing_onStart_134 },
    { 135, stub_GTRacing_onStop_135 },
    { 137, stub_GTRacing_onUserInteraction_137 },
    { 138, stub_GTRacing_openCustomerCare_138 },
    { 139, stub_GTRacing_showOffersWithCurrencyID_139 },
    { 140, stub_GTRacing_surfaceChanged_140 },
    { 141, stub_GTRacing_surfaceCreated_141 },
    { 142, stub_GTRacing_surfaceDestroyed_142 },
    { 144, stub_GameGLSurfaceView_onPause_144 },
    { 145, stub_GameGLSurfaceView_onResume_145 },
    { 146, stub_GameGLSurfaceView_onSizeChanged_146 },
    { 147, stub_GameGLSurfaceView_onWindowFocusChanged_147 },
    { 149, stub_GameRenderer_onDrawFrame_149 },
    { 150, stub_GameRenderer_onSurfaceChanged_150 },
    { 151, stub_GameRenderer_onSurfaceCreated_151 },
    { 153, stub_IGPFreemiumActivity_a_153 },
    { 154, stub_IGPFreemiumActivity_a_154 },
    { 155, stub_IGPFreemiumActivity_b_155 },
    { 157, stub_IGPFreemiumActivity_a_157 },
    { 158, stub_IGPFreemiumActivity_onCreate_158 },
    { 159, stub_IGPFreemiumActivity_onDestroy_159 },
    { 163, stub_IGPFreemiumActivity_onPause_163 },
    { 164, stub_IGPFreemiumActivity_onResume_164 },
    { 165, stub_IGPFreemiumActivity_onStart_165 },
    { 166, stub_IGPFreemiumActivity_onStop_166 },
    { 167, stub_IGPFreemiumActivity_onWindowFocusChanged_167 },
    { 168, stub_KeyboardInput_onCreate_168 },
    { 172, stub_FacebookAndroidGLSocialLib_AuthorizeSSOCallback_172 },
    { 173, stub_FacebookAndroidGLSocialLib_ClearAuth_173 },
    { 174, stub_FacebookAndroidGLSocialLib_GetFriends_174 },
    { 175, stub_FacebookAndroidGLSocialLib_GetFriendsInGame_175 },
    { 176, stub_FacebookAndroidGLSocialLib_GetMyInfo_176 },
    { 177, stub_FacebookAndroidGLSocialLib_GetPicture_177 },
    { 178, stub_FacebookAndroidGLSocialLib_GetUserData_178 },
    { 179, stub_FacebookAndroidGLSocialLib_Init_179 },
    { 180, stub_FacebookAndroidGLSocialLib_InviteFriends_180 },
    { 181, stub_FacebookAndroidGLSocialLib_InviteFriends_facade_181 },
    { 184, stub_FacebookAndroidGLSocialLib_Login_184 },
    { 185, stub_FacebookAndroidGLSocialLib_Login_facade_185 },
    { 186, stub_FacebookAndroidGLSocialLib_Logout_186 },
    { 187, stub_FacebookAndroidGLSocialLib_PostToFriendsWall_187 },
    { 188, stub_FacebookAndroidGLSocialLib_PostToFriendsWall_facade_188 },
    { 189, stub_FacebookAndroidGLSocialLib_PostToWall_189 },
    { 190, stub_FacebookAndroidGLSocialLib_PostToWall_facade_190 },
    { 192, stub_FacebookAndroidGLSocialLib_SetAppId_192 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 16, stub_Device_createUniqueCode_16 },
    { 40, stub_Device_getUniqueCode_40 },
    { 64, stub_SUtils_getPreferenceInt_64 },
    { 71, stub_SUtils_getUniqueCode_71 },
    { 102, stub_GTRacing_getManufacture_102 },
    { 115, stub_GTRacing_EnableAutoRotateScreen_115 },
};

// Candidate methodsFloat[] entries -- append into the real methodsFloat[] in java.c
static const MethodsFloat generated_methodsFloat[] = {
    { 54, stub_SUtils_getFreeSpace_54 },
};

// Candidate methodsLong[] entries -- append into the real methodsLong[] in java.c
static const MethodsLong generated_methodsLong[] = {
    { 65, stub_SUtils_getPreferenceLong_65 },
};

